### ISSUE TITLE
Problem parsing double quoted tokens

### ISSUE THREAD

**Issue by SimonGreenhill** [ropensci/bib2df#30]
In the following BibTeX file:

```bib
@phdthesis{Yang2011Lalo,
    author = {Yang, Cathryn},
    address = {Bundoora},
    language = {English},
    school = {La Trobe University},
    shorttitle = {Lalo regional varieties},
    title = {Lalo regional varieties: {Phylogeny}, dialectometry and sociolinguistics},
    type = {{PhD} dissertation},
    year = {2011}
}
```

... the field `type` gets parsed to `PhD} dissertation` (i.e. the first curly brace protecting the casing in 'PhD' gets eaten. 

The culprit is [this statement](https://github.com/ropensci/bib2df/blob/master/R/bib2df_gather.R#L57) in `bib_gather`. I'm not quite sure what this regex is doing, so I don't want to fiddle with it to fix it.

**Comment by ottlngr** [comment]
Hi, thanks for your message.

I'll look into this, but it seems like this can be solved easily!

**Comment by ottlngr** [comment]
Solved by e64df0e8af04ea2b5c8e4efd1eb2f8734e932e8e

**Comment by SimonGreenhill** [comment]
great! thanks!

**Comment by ottlngr** [comment]
But beware that the fix is currently only available in branch v1.1.2. To install this version of `bib2df`, run `remotes::install_github("ropensci/bib2df@v1.1.2")`. This version may not be stable yet, though.

**Comment by agricolamz** [comment]
Hi, 

I think the problem is still remain when the bracket is in the end of the name field:

Here is a `.bib` file:
```
@Inproceedings{brugman04,
  Author = {Brugman, H. and Russel, A. and Nijmegen, X.},
  Booktitle = {LREC},
  Title = {Annotating {M}ulti-media/{M}ulti-modal {R}esources with {ELAN}},
  Year = {2004}
}
```
Here is the code:
```
bib2df("test.bib") %>% 
   unlist() %>% 
   na.omit() %>% 
   View()
```
Here is the result:
```
CATEGORY	INPROCEEDINGS
BIBTEXKEY	brugman04
AUTHOR1	Brugman, H.
AUTHOR2	Russel, A.
AUTHOR3	Nijmegen, X.
BOOKTITLE	LREC
TITLE	Annotating {M}ulti-media/{M}ulti-modal {R}esources with {ELAN
YEAR	2004
```
As you can see it should've been `{ELAN}`.

I'm using `bib2df` v. 1.1.1
